### ISSUE TITLE
Naming of chromosome M/MT

### ISSUE THREAD

**Issue by zedrdave** [BenLangmead/bowtie-majref#1]
I'm using the `grch38_1kgmaj.fa` reference sequence and associated Bowtie2 index, but having a hard time understanding why chromosomes all use the standard Ensembl nomenclature (`1`, `2`, `X` etc), except for Mitochondrial DNA: `M` (instead of `MT` in Ensembl).

Is this possibly a bug due to an overzealous `sed` command?

**Comment by milkschen** [comment]
Hi, thank you for reporting this issue. 

We have updated the script to build the major-allele reference for GRCh38. Now it follows the naming of GRCh38 (chr1, chr2, chrM, ...). The pre-built indexes for Bowtie and Bowtie 2 websites have also been updated.

The major-allele reference and its indexes for GRCh37 remain unchanged (1, 2, M, ...).
