### ISSUE TITLE
the ftp site links are switched in the README.md

### ISSUE THREAD

**Issue by MADscientist314** [BenLangmead/bowtie-majref#2]
Hi there.  I noticed in the README that the ftp sites are switched:

Bowtie 2 | GRCh38 + major SNPs | ftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/hg19_1kgmaj_bt2.zip
-- | -- | --
Bowtie 2 | hg19 + major SNPs | ftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/grch38_1kgmaj_bt2.zip

**Comment by mmahmoudian** [comment]
I came to report the same thing:

![image](https://user-images.githubusercontent.com/390889/95837627-77e1ea00-0d49-11eb-945f-0cbedbebe587.png)

**Comment by milkschen** [comment]
Thank you for pointing this out. We have fixed the mis-placement in the document.
